# Generated by Django 5.0.1 on 2024-02-03 08:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedbooks',
            name='added_by_user_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], size=None),
            preserve_default=False,
        ),
    ]
