# Generated by Django 5.0.1 on 2024-02-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_listing', '0003_listedbooks_is_deleted_listedbooks_state_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedbooks',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
